#!/bin/sh

# build markdown into HTML
showdown makehtml -i index.md -o partials/body.html

# write all the partial files in concatenation to index.html
cd partials/
cat head.html profileimage.html aside.html body.html footer.html > ../index.html
cd ..

echo "Built index.html."
