#!/bin/sh

# build markdown into HTML
showdown makehtml -i index.md -o partials/body.html

# write all the partial files in concatenation to index.html
cat partials/head.html partials/profileimage.html partials/aside.html partials/body.html > index.html

echo "Built index.html."
